version: "3"

services:
  db:
    image: mariadb:10.4
    container_name: db_mariadb
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mariadb/db:/var/lib/mysql
    restart: unless-stopped
  db2:
    image: mariadb:10.4
    container_name: db2_mariadb
    ports:
      - ${DB2_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: ${DB2_NAME}
      MYSQL_USER: ${DB2_USER}
      MYSQL_PASSWORD: ${DB2_PASSWORD}
    volumes:
      - ./mariadb/db2:/var/lib/mysql
    restart: unless-stopped
