interface SheetConfig {
  source: { columns: string[] }
  destinations: { name: string; columns: string[] }[]
}

export const sheetConfig: SheetConfig = {
  source: {
    columns: [
      'no',
      'nama',
      'jns_identitas',
      'nik',
      'tgl_lahir',
      'usia_thn',
      'usia_bln',
      'jkel',
      'telp',
      'alamat_domisili',
      'alamat_propkd',
      'alamat_propnm',
      'alamat_kabkd',
      'alamat_kabnm',
      'alamat_keckd',
      'alamat_kecnm',
      'alamat_kelkd',
      'alamat_kelnm',
      'alamat_rw',
      'alamat_rt',
      'warganegara',
      'warganegara_ket',
      'tujuan_periksa',
      'faskes_jns',
      'faskes_nm',
      'faskes_propkd',
      'faskes_propnm',
      'faskes_kabkd',
      'faskes_kabnm',
      'pembiayaan',
      'tgl_gejala',
      'no_spesimen',
      'no_pemeriksaan',
      'jns_spesimen',
      'tgl_pengambilan',
      'tgl_hasil',
      'hsl_lab',
      'created_date',
    ],
  },
  destinations: [
    {
      name: 'patient',
      columns: [
        'nama',
        'jns_identitas',
        'nik',
        'tgl_lahir',
        'usia_thn',
        'usia_bln',
        'jkel',
        'telp',
        'alamat_domisili',
        'alamat_propkd',
        'alamat_propnm',
        'alamat_kabkd',
        'alamat_kabnm',
        'alamat_keckd',
        'alamat_kecnm',
        'alamat_kelkd',
        'alamat_kelnm',
        'alamat_rw',
        'alamat_rt',
        'warganegara',
        'warganegara_ket',
        'faskes_nm',
        'faskes_propkd',
        'faskes_propnm',
        'faskes_kabkd',
        'faskes_kabnm',
        'hsl_lab',
        'created_date',
      ],
    },
    {
      name: 'specimen',
      columns: [
        'jns_identitas',
        'nik',
        'tgl_lahir',
        'usia_thn',
        'usia_bln',
        'jkel',
        'telp',
        'alamat_domisili',
        'alamat_propkd',
        'alamat_propnm',
        'alamat_kabkd',
        'alamat_kabnm',
        'alamat_keckd',
        'alamat_kecnm',
        'alamat_kelkd',
        'alamat_kelnm',
        'alamat_rw',
        'alamat_rt',
        'warganegara',
        'warganegara_ket',
        'tujuan_periksa',
        'faskes_jns',
        'faskes_nm',
        'faskes_propkd',
        'faskes_propnm',
        'faskes_kabkd',
        'faskes_kabnm',
        'pembiayaan',
        'tgl_gejala',
        'no_spesimen',
        'no_pemeriksaan',
        'jns_spesimen',
        'tgl_pengambilan',
        'tgl_hasil',
        'hsl_lab',
        'created_date',
      ],
    },
  ],
}
