interface SheetConfig {
  [type: string]: {
    destinations: {
      kind: string
      columnRange: string
      columns: { name: string; type?: string }[]
    }[]
  }
}

// TODO: Remove hardcode
export const sheetConfig: SheetConfig = {
  pcr: {
    destinations: [
      {
        kind: 'patient',
        columnRange: 'B-V,X-AD,AK-AN,AR-AT',
        columns: [
          { name: 'nama' },
          { name: 'jns_identitas' },
          { name: 'nik' },
          { name: 'tgl_lahir' },
          { name: 'usia_thn' },
          { name: 'usia_bln' },
          { name: 'jkel' },
          { name: 'telp' },
          { name: 'alamat_domisili' },
          { name: 'alamat_propkd' },
          { name: 'alamat_propnm' },
          { name: 'alamat_kabkd' },
          { name: 'alamat_kabnm' },
          { name: 'alamat_keckd' },
          { name: 'alamat_kecnm' },
          { name: 'alamat_kelkd' },
          { name: 'alamat_kelnm' },
          { name: 'alamat_rw' },
          { name: 'alamat_rt' },
          { name: 'warganegara' },
          { name: 'warganegara_ket' },
          { name: 'tgl_gejala' },
          { name: 'faskes_jns' },
          { name: 'faskes_nm' },
          { name: 'faskes_propkd' },
          { name: 'faskes_propnm' },
          { name: 'faskes_kabkd' },
          { name: 'faskes_kabnm' },
          { name: 'created_by' },
          { name: 'created_date' },
          { name: 'lab_kd' },
          { name: 'lab_nm' },
          { name: 'hsl_lab' },
          { name: 'verif_by' },
          { name: 'verif_date' },
          // column is not available in sheet
          { name: 'alamat' },
          { name: 'faskes_kd' },
          { name: 'faskes_ket' },
          { name: 'created_id' },
          { name: 'modified_id' },
          { name: 'modified_by' },
          { name: 'modified_date' },
          { name: 'verif_id' },
          { name: 'bantu_dump_nar' },
        ],
      },
      {
        kind: 'specimen',
        columnRange: 'B-AT',
        columns: [
          { name: 'nama' },
          { name: 'jns_identitas' },
          { name: 'nik' },
          { name: 'tgl_lahir' },
          { name: 'usia_thn' },
          { name: 'usia_bln' },
          { name: 'jkel' },
          { name: 'telp' },
          { name: 'alamat_domisili' },
          { name: 'alamat_propkd' },
          { name: 'alamat_propnm' },
          { name: 'alamat_kabkd' },
          { name: 'alamat_kabnm' },
          { name: 'alamat_keckd' },
          { name: 'alamat_kecnm' },
          { name: 'alamat_kelkd' },
          { name: 'alamat_kelnm' },
          { name: 'alamat_rw' },
          { name: 'alamat_rt' },
          { name: 'warganegara' },
          { name: 'warganegara_ket' },
          { name: 'tujuan_periksa' },
          { name: 'tgl_gejala' },
          { name: 'faskes_jns' },
          { name: 'faskes_nm' },
          { name: 'faskes_propkd' },
          { name: 'faskes_propnm' },
          { name: 'faskes_kabkd' },
          { name: 'faskes_kabnm' },
          { name: 'pembiayaan' },
          { name: 'no_lab' },
          { name: 'no_pemeriksaan' },
          { name: 'jns_spesimen' },
          { name: 'tgl_pengambilan' },
          { name: 'tgl_kirim' },
          { name: 'created_by' },
          { name: 'created_date' },
          { name: 'kd_lab' },
          { name: 'nm_lab' },
          { name: 'tgl_terima' },
          { name: 'tgl_periksa' },
          { name: 'tgl_hasil' },
          { name: 'hsl_lab' },
          { name: 'verif_by' },
          { name: 'verif_date' },
          // column is not available in sheet
          { name: 'id', type: 'int' },
          { name: 'alamat' },
          { name: 'faskes_kd' },
          { name: 'faskes_ket' },
          { name: 'created_id' },
          { name: 'modified_id' },
          { name: 'modified_date' },
          { name: 'verif_id' },
          { name: 'bantu_dump_nar' },
          { name: 'akun_ehac' },
          { name: 'lab_tujuan_kd' },
          { name: 'lab_tujuan_nm' },
        ],
      },
    ],
  },
  antigen: {
    destinations: [
      {
        kind: 'patient',
        columnRange: 'B-V,Y-AC,AK-AL',
        columns: [
          { name: 'nama' },
          { name: 'jns_identitas', type: 'int' },
          { name: 'nik' },
          { name: 'tgl_lahir' },
          { name: 'usia_thn' },
          { name: 'usia_bln' },
          { name: 'jkel' },
          { name: 'telp' },
          { name: 'alamat_domisili' },
          { name: 'alamat_propkd' },
          { name: 'alamat_propnm' },
          { name: 'alamat_kabkd' },
          { name: 'alamat_kabnm' },
          { name: 'alamat_keckd' },
          { name: 'alamat_kecnm' },
          { name: 'alamat_kelkd', type: 'int' },
          { name: 'alamat_kelnm' },
          { name: 'alamat_rw' },
          { name: 'alamat_rt' },
          { name: 'warganegara' },
          { name: 'warganegara_ket' },
          { name: 'faskes_nm' },
          { name: 'faskes_propkd' },
          { name: 'faskes_propnm' },
          { name: 'faskes_kabkd' },
          { name: 'faskes_kabnm' },
          { name: 'hsl_lab' },
          { name: 'created_date' },
          // column is not available in sheet
          { name: 'alamat_ktp' },
          { name: 'created_id' },
          { name: 'bantu' },
        ],
      },
      {
        kind: 'specimen',
        columnRange: 'B-AL',
        columns: [
          { name: 'nama' },
          { name: 'jns_identitas' },
          { name: 'nik' },
          { name: 'tgl_lahir' },
          { name: 'usia_thn' },
          { name: 'usia_bln' },
          { name: 'jkel' },
          { name: 'telp' },
          { name: 'alamat_domisili' },
          { name: 'alamat_propkd' },
          { name: 'alamat_propnm' },
          { name: 'alamat_kabkd' },
          { name: 'alamat_kabnm' },
          { name: 'alamat_keckd' },
          { name: 'alamat_kecnm' },
          { name: 'alamat_kelkd' },
          { name: 'alamat_kelnm' },
          { name: 'alamat_rw' },
          { name: 'alamat_rt' },
          { name: 'warganegara' },
          { name: 'warganegara_ket' },
          { name: 'tujuan_periksa' },
          { name: 'faskes_jns' },
          { name: 'faskes_nm' },
          { name: 'faskes_propkd' },
          { name: 'faskes_propnm' },
          { name: 'faskes_kabkd' },
          { name: 'faskes_kabnm' },
          { name: 'pembiayaan' },
          { name: 'tgl_gejala' },
          { name: 'no_spesimen' },
          { name: 'no_pemeriksaan' },
          { name: 'jns_spesimen' },
          { name: 'tgl_pengambilan' },
          { name: 'tgl_hasil' },
          { name: 'hsl_lab' },
          { name: 'created_date' },
          // column is not available in sheet
          { name: 'alamat_ktp' },
          { name: 'created_id' },
          { name: 'bantu' },
        ],
      },
    ],
  },
}
